//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveIt.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Key {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Key() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoveIt.Localization.Key", typeof(Key).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulldoze.
        /// </summary>
        internal static string main_Bulldoze {
            get {
                return ResourceManager.GetString("main_Bulldoze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string main_Clone {
            get {
                return ResourceManager.GetString("main_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        internal static string main_DeselectAll {
            get {
                return ResourceManager.GetString("main_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string main_MoveDown {
            get {
                return ResourceManager.GetString("main_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move East.
        /// </summary>
        internal static string main_MoveEast {
            get {
                return ResourceManager.GetString("main_MoveEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move North.
        /// </summary>
        internal static string main_MoveNorth {
            get {
                return ResourceManager.GetString("main_MoveNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move South.
        /// </summary>
        internal static string main_MoveSouth {
            get {
                return ResourceManager.GetString("main_MoveSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string main_MoveUp {
            get {
                return ResourceManager.GetString("main_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move West.
        /// </summary>
        internal static string main_MoveWest {
            get {
                return ResourceManager.GetString("main_MoveWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string main_Redo {
            get {
                return ResourceManager.GetString("main_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Counterclockwise.
        /// </summary>
        internal static string main_RotateCCW {
            get {
                return ResourceManager.GetString("main_RotateCCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Clockwise.
        /// </summary>
        internal static string main_RotateCW {
            get {
                return ResourceManager.GetString("main_RotateCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Inwards.
        /// </summary>
        internal static string main_ScaleIn {
            get {
                return ResourceManager.GetString("main_ScaleIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Outwards.
        /// </summary>
        internal static string main_ScaleOut {
            get {
                return ResourceManager.GetString("main_ScaleOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Over.
        /// </summary>
        internal static string main_StepOver {
            get {
                return ResourceManager.GetString("main_StepOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Debug Panel.
        /// </summary>
        internal static string main_ToggleDebugPanel {
            get {
                return ResourceManager.GetString("main_ToggleDebugPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Grid View.
        /// </summary>
        internal static string main_ToggleGridView {
            get {
                return ResourceManager.GetString("main_ToggleGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Tool.
        /// </summary>
        internal static string main_ToggleTool {
            get {
                return ResourceManager.GetString("main_ToggleTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Underground View.
        /// </summary>
        internal static string main_ToggleUndergroundView {
            get {
                return ResourceManager.GetString("main_ToggleUndergroundView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string main_Undo {
            get {
                return ResourceManager.GetString("main_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Slope.
        /// </summary>
        internal static string tool_FullSlope {
            get {
                return ResourceManager.GetString("tool_FullSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Up (Spaced).
        /// </summary>
        internal static string tool_LineUpSpaced {
            get {
                return ResourceManager.GetString("tool_LineUpSpaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Up (Unspaced).
        /// </summary>
        internal static string tool_LineUpUnspaced {
            get {
                return ResourceManager.GetString("tool_LineUpUnspaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Objects.
        /// </summary>
        internal static string tool_MirrorObjects {
            get {
                return ResourceManager.GetString("tool_MirrorObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Slope Node.
        /// </summary>
        internal static string tool_QuickSlopeNode {
            get {
                return ResourceManager.GetString("tool_QuickSlopeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Objects.
        /// </summary>
        internal static string tool_ResetObjects {
            get {
                return ResourceManager.GetString("tool_ResetObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate At Centre.
        /// </summary>
        internal static string tool_RotateAtCentre {
            get {
                return ResourceManager.GetString("tool_RotateAtCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate In-Place.
        /// </summary>
        internal static string tool_RotateInPlace {
            get {
                return ResourceManager.GetString("tool_RotateInPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Randomly.
        /// </summary>
        internal static string tool_RotateRandomly {
            get {
                return ResourceManager.GetString("tool_RotateRandomly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Position.
        /// </summary>
        internal static string tool_SetPosition {
            get {
                return ResourceManager.GetString("tool_SetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope Objects.
        /// </summary>
        internal static string tool_SlopeObjects {
            get {
                return ResourceManager.GetString("tool_SlopeObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align To Object Height.
        /// </summary>
        internal static string tool_ToObjectHeight {
            get {
                return ResourceManager.GetString("tool_ToObjectHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align To Terrain Height.
        /// </summary>
        internal static string tool_ToTerrainHeight {
            get {
                return ResourceManager.GetString("tool_ToTerrainHeight", resourceCulture);
            }
        }
    }
}
