//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveIt.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoveIt.Localization.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulldoze.
        /// </summary>
        internal static string baseUI_Bulldoze_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_Bulldoze_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Alt+Click to duplicate in-place).
        /// </summary>
        internal static string baseUI_Clone_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_Clone_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Terrain.
        /// </summary>
        internal static string baseUI_FollowTerrain_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_FollowTerrain_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marquee Selection.
        /// </summary>
        internal static string baseUI_Marquee_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_Marquee_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoconnect Cloned Nodes.
        /// </summary>
        internal static string baseUI_MergeNodesTooltip {
            get {
                return ResourceManager.GetString("baseUI_MergeNodesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move It.
        /// </summary>
        internal static string baseUI_MoveItButton_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_MoveItButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Selection.
        /// </summary>
        internal static string baseUI_Single_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_Single_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Grid.
        /// </summary>
        internal static string baseUI_ToggleGrid_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_ToggleGrid_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Procedural Objects.
        /// </summary>
        internal static string baseUI_TogglePO_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_TogglePO_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Snapping.
        /// </summary>
        internal static string baseUI_ToggleSnapping_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_ToggleSnapping_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Underground View.
        /// </summary>
        internal static string baseUI_ToggleUnderground_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_ToggleUnderground_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        internal static string baseUI_Toolbox_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_Toolbox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        internal static string filter_Buildings {
            get {
                return ResourceManager.GetString("filter_Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decals.
        /// </summary>
        internal static string filter_Decals {
            get {
                return ResourceManager.GetString("filter_Decals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fences.
        /// </summary>
        internal static string filter_Fences {
            get {
                return ResourceManager.GetString("filter_Fences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes.
        /// </summary>
        internal static string filter_Nodes {
            get {
                return ResourceManager.GetString("filter_Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string filter_Others {
            get {
                return ResourceManager.GetString("filter_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        internal static string filter_Paths {
            get {
                return ResourceManager.GetString("filter_Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker.
        /// </summary>
        internal static string filter_Picker {
            get {
                return ResourceManager.GetString("filter_Picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick an object to filter for objects of the same type.
        /// </summary>
        internal static string filter_Picker_Tooltip {
            get {
                return ResourceManager.GetString("filter_Picker_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO.
        /// </summary>
        internal static string filter_PO {
            get {
                return ResourceManager.GetString("filter_PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerlines.
        /// </summary>
        internal static string filter_Powerlines {
            get {
                return ResourceManager.GetString("filter_Powerlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Props.
        /// </summary>
        internal static string filter_Props {
            get {
                return ResourceManager.GetString("filter_Props", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roads.
        /// </summary>
        internal static string filter_Roads {
            get {
                return ResourceManager.GetString("filter_Roads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segments.
        /// </summary>
        internal static string filter_Segments {
            get {
                return ResourceManager.GetString("filter_Segments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surfaces.
        /// </summary>
        internal static string filter_Surfaces {
            get {
                return ResourceManager.GetString("filter_Surfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        internal static string filter_Tracks {
            get {
                return ResourceManager.GetString("filter_Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trees.
        /// </summary>
        internal static string filter_Trees {
            get {
                return ResourceManager.GetString("filter_Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Skins 2 found, integration enabled!.
        /// </summary>
        internal static string integration_NS2_Found {
            get {
                return ResourceManager.GetString("integration_NS2_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Skins 2 not found, or NS1 and NS2 both subscribed, integration disabled..
        /// </summary>
        internal static string integration_NS2_Notfound {
            get {
                return ResourceManager.GetString("integration_NS2_Notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO version {0} found, integration enabled!.
        /// </summary>
        internal static string integration_PO_Found {
            get {
                return ResourceManager.GetString("integration_PO_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO not found, integration disabled..
        /// </summary>
        internal static string integration_PO_Notfound {
            get {
                return ResourceManager.GetString("integration_PO_Notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO integration failed - found version {0} (required: 1.7).
        /// </summary>
        internal static string integration_PO_WrongVersion {
            get {
                return ResourceManager.GetString("integration_PO_WrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulldoze.
        /// </summary>
        internal static string key_Bulldoze {
            get {
                return ResourceManager.GetString("key_Bulldoze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string key_Clone {
            get {
                return ResourceManager.GetString("key_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert selected objects to PO.
        /// </summary>
        internal static string key_ConvertToPO {
            get {
                return ResourceManager.GetString("key_ConvertToPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        internal static string key_DeselectAll {
            get {
                return ResourceManager.GetString("key_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string key_MoveDown {
            get {
                return ResourceManager.GetString("key_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move East.
        /// </summary>
        internal static string key_MoveEast {
            get {
                return ResourceManager.GetString("key_MoveEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move North.
        /// </summary>
        internal static string key_MoveNorth {
            get {
                return ResourceManager.GetString("key_MoveNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move South.
        /// </summary>
        internal static string key_MoveSouth {
            get {
                return ResourceManager.GetString("key_MoveSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string key_MoveUp {
            get {
                return ResourceManager.GetString("key_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move West.
        /// </summary>
        internal static string key_MoveWest {
            get {
                return ResourceManager.GetString("key_MoveWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold for Underground View.
        /// </summary>
        internal static string key_QuickUndergroundView {
            get {
                return ResourceManager.GetString("key_QuickUndergroundView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string key_Redo {
            get {
                return ResourceManager.GetString("key_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Counterclockwise.
        /// </summary>
        internal static string key_RotateCCW {
            get {
                return ResourceManager.GetString("key_RotateCCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Clockwise.
        /// </summary>
        internal static string key_RotateCW {
            get {
                return ResourceManager.GetString("key_RotateCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Inwards.
        /// </summary>
        internal static string key_ScaleIn {
            get {
                return ResourceManager.GetString("key_ScaleIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Outwards.
        /// </summary>
        internal static string key_ScaleOut {
            get {
                return ResourceManager.GetString("key_ScaleOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Selectors.
        /// </summary>
        internal static string key_ShowSelectors {
            get {
                return ResourceManager.GetString("key_ShowSelectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Over.
        /// </summary>
        internal static string key_StepOver {
            get {
                return ResourceManager.GetString("key_StepOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Debug Panel.
        /// </summary>
        internal static string key_ToggleDebugPanel {
            get {
                return ResourceManager.GetString("key_ToggleDebugPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Grid View.
        /// </summary>
        internal static string key_ToggleGridView {
            get {
                return ResourceManager.GetString("key_ToggleGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle PO Active/Inactive.
        /// </summary>
        internal static string key_TogglePO {
            get {
                return ResourceManager.GetString("key_TogglePO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Tool.
        /// </summary>
        internal static string key_ToggleTool {
            get {
                return ResourceManager.GetString("key_ToggleTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Underground View.
        /// </summary>
        internal static string key_ToggleUndergroundView {
            get {
                return ResourceManager.GetString("key_ToggleUndergroundView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Slope.
        /// </summary>
        internal static string key_ToolFullSlope {
            get {
                return ResourceManager.GetString("key_ToolFullSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Up (Spaced).
        /// </summary>
        internal static string key_ToolLineUpSpaced {
            get {
                return ResourceManager.GetString("key_ToolLineUpSpaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Up (Unspaced).
        /// </summary>
        internal static string key_ToolLineUpUnspaced {
            get {
                return ResourceManager.GetString("key_ToolLineUpUnspaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Objects.
        /// </summary>
        internal static string key_ToolMirrorObjects {
            get {
                return ResourceManager.GetString("key_ToolMirrorObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Slope Node.
        /// </summary>
        internal static string key_ToolQuickSlopeNode {
            get {
                return ResourceManager.GetString("key_ToolQuickSlopeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Objects.
        /// </summary>
        internal static string key_ToolResetObjects {
            get {
                return ResourceManager.GetString("key_ToolResetObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate At Centre.
        /// </summary>
        internal static string key_ToolRotateAtCentre {
            get {
                return ResourceManager.GetString("key_ToolRotateAtCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate In-Place.
        /// </summary>
        internal static string key_ToolRotateInPlace {
            get {
                return ResourceManager.GetString("key_ToolRotateInPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Randomly.
        /// </summary>
        internal static string key_ToolRotateRandomly {
            get {
                return ResourceManager.GetString("key_ToolRotateRandomly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Position.
        /// </summary>
        internal static string key_ToolSetPosition {
            get {
                return ResourceManager.GetString("key_ToolSetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope Objects.
        /// </summary>
        internal static string key_ToolSlopeObjects {
            get {
                return ResourceManager.GetString("key_ToolSlopeObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align To Object Height.
        /// </summary>
        internal static string key_ToolToObjectHeight {
            get {
                return ResourceManager.GetString("key_ToolToObjectHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align To Terrain Height.
        /// </summary>
        internal static string key_ToolToTerrainHeight {
            get {
                return ResourceManager.GetString("key_ToolToTerrainHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string key_Undo {
            get {
                return ResourceManager.GetString("key_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move things.
        /// </summary>
        internal static string mod_description {
            get {
                return ResourceManager.GetString("mod_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Advanced Pillar Control.
        /// </summary>
        internal static string options_AdvancedPillarControl {
            get {
                return ResourceManager.GetString("options_AdvancedPillarControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows fine control of pillars and pylons - the game will not reset their position, but can cause terrain glitches that requires Surface Painter to remove..
        /// </summary>
        internal static string options_AdvancedPillarControl_Tooltip {
            get {
                return ResourceManager.GetString("options_AdvancedPillarControl_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select pylons and pillars by holding Alt only.
        /// </summary>
        internal static string options_AltForPillars {
            get {
                return ResourceManager.GetString("options_AltForPillars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-close Toolbox menu.
        /// </summary>
        internal static string options_AutoCloseToolbox {
            get {
                return ResourceManager.GetString("options_AutoCloseToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this to close the Toolbox menu after choosing a tool..
        /// </summary>
        internal static string options_AutoCloseToolbox_Tooltip {
            get {
                return ResourceManager.GetString("options_AutoCloseToolbox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please support the development of Move It and my other mods..
        /// </summary>
        internal static string options_Beg {
            get {
                return ResourceManager.GetString("options_Beg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable debug messages logging.
        /// </summary>
        internal static string options_DisableDebugLogging {
            get {
                return ResourceManager.GetString("options_DisableDebugLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, debug messages won&apos;t be logged..
        /// </summary>
        internal static string options_DisableDebugLogging_Tooltip {
            get {
                return ResourceManager.GetString("options_DisableDebugLogging_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Options.
        /// </summary>
        internal static string options_ExtraOptions {
            get {
                return ResourceManager.GetString("options_ExtraOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Tree Snapping.
        /// </summary>
        internal static string options_fixTreeSnapping {
            get {
                return ResourceManager.GetString("options_fixTreeSnapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Tree Snapping is causing tree heights to be off, click this straight after loading your city..
        /// </summary>
        internal static string options_fixTreeSnappingTooltip {
            get {
                return ResourceManager.GetString("options_fixTreeSnappingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the PO deletion warning.
        /// </summary>
        internal static string options_HidePODeletionWarning {
            get {
                return ResourceManager.GetString("options_HidePODeletionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string options_Options {
            get {
                return ResourceManager.GetString("options_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patreon.
        /// </summary>
        internal static string options_Patreon {
            get {
                return ResourceManager.GetString("options_Patreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support me on Patreon.
        /// </summary>
        internal static string options_PatreonTooltip {
            get {
                return ResourceManager.GetString("options_PatreonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal.
        /// </summary>
        internal static string options_Paypal {
            get {
                return ResourceManager.GetString("options_Paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support me on Paypal.
        /// </summary>
        internal static string options_PaypalTooltip {
            get {
                return ResourceManager.GetString("options_PaypalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note: you can not undo Bulldozed PO. This means if you delete
        ///PO objects with Move It, they are immediately PERMANENTLY gone..
        /// </summary>
        internal static string options_PODeleteWarning {
            get {
                return ResourceManager.GetString("options_PODeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer fast, low-detail moving (hold Shift to temporarily switch).
        /// </summary>
        internal static string options_PreferFastmove {
            get {
                return ResourceManager.GetString("options_PreferFastmove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helps you position objects when your frame-rate is poor..
        /// </summary>
        internal static string options_PreferFastmove_Tooltip {
            get {
                return ResourceManager.GetString("options_PreferFastmove_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedural Objects.
        /// </summary>
        internal static string options_ProceduralObjects {
            get {
                return ResourceManager.GetString("options_ProceduralObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Ghost Nodes.
        /// </summary>
        internal static string options_RemoveGhostNodes {
            get {
                return ResourceManager.GetString("options_RemoveGhostNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this button when in-game to remove ghost nodes (nodes with no segments attached). Note: this will clear Move It&apos;s undo history!.
        /// </summary>
        internal static string options_RemoveGhostNodes_Tooltip {
            get {
                return ResourceManager.GetString("options_RemoveGhostNodes_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Button Position.
        /// </summary>
        internal static string options_ResetButtonPosition {
            get {
                return ResourceManager.GetString("options_ResetButtonPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click cancels cloning.
        /// </summary>
        internal static string options_RightClickCancel {
            get {
                return ResourceManager.GetString("options_RightClickCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, Right click will cancel cloning instead of rotating 45°..
        /// </summary>
        internal static string options_RightClickCancel_Tooltip {
            get {
                return ResourceManager.GetString("options_RightClickCancel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Shortcuts.
        /// </summary>
        internal static string options_ShortcutsGeneral {
            get {
                return ResourceManager.GetString("options_ShortcutsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Shortcuts.
        /// </summary>
        internal static string options_ShortcutsToolbox {
            get {
                return ResourceManager.GetString("options_ShortcutsToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Move It debug panel.
        /// </summary>
        internal static string options_ShowDebugPanel {
            get {
                return ResourceManager.GetString("options_ShowDebugPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Move It to select everything. Use with care!.
        /// </summary>
        internal static string options_superSelect {
            get {
                return ResourceManager.GetString("options_superSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will let Move It select everything. Do not use this unless you know exactly what you are doing.
        ///
        ///THIS IS EXTREMELY POWERFUL AND WILL BREAK YOUR CITY!.
        /// </summary>
        internal static string options_superSelect_Tooltip {
            get {
                return ResourceManager.GetString("options_superSelect_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use compass movements.
        /// </summary>
        internal static string options_UseCompass {
            get {
                return ResourceManager.GetString("options_UseCompass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the Up key will move in the North direction, Down is South, Left is West, Right is East..
        /// </summary>
        internal static string options_UseCompass_Tooltip {
            get {
                return ResourceManager.GetString("options_UseCompass_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use UnifiedUI.
        /// </summary>
        internal static string options_UseUUI {
            get {
                return ResourceManager.GetString("options_UseUUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string setpos_A_Tooltip {
            get {
                return ResourceManager.GetString("setpos_A_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string setpos_Go {
            get {
                return ResourceManager.GetString("setpos_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string setpos_H_Tooltip {
            get {
                return ResourceManager.GetString("setpos_H_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string setpos_Title {
            get {
                return ResourceManager.GetString("setpos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert To PO.
        /// </summary>
        internal static string toolbox_ConvertToPO {
            get {
                return ResourceManager.GetString("toolbox_ConvertToPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Selection.
        /// </summary>
        internal static string toolbox_ExportSelection {
            get {
                return ResourceManager.GetString("toolbox_ExportSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Tools.
        /// </summary>
        internal static string toolbox_HeightTools_Tooltip {
            get {
                return ResourceManager.GetString("toolbox_HeightTools_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Selection.
        /// </summary>
        internal static string toolbox_ImportSelection {
            get {
                return ResourceManager.GetString("toolbox_ImportSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Up Objects.
        /// </summary>
        internal static string toolbox_LineUpObjects {
            get {
                return ResourceManager.GetString("toolbox_LineUpObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Objects.
        /// </summary>
        internal static string toolbox_MirrorObjects {
            get {
                return ResourceManager.GetString("toolbox_MirrorObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Tools.
        /// </summary>
        internal static string toolbox_OtherTools_Tooltip {
            get {
                return ResourceManager.GetString("toolbox_OtherTools_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Objects.
        /// </summary>
        internal static string toolbox_ResetObjects {
            get {
                return ResourceManager.GetString("toolbox_ResetObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate At Centre.
        /// </summary>
        internal static string toolbox_RotateAtCentre {
            get {
                return ResourceManager.GetString("toolbox_RotateAtCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate In-Place.
        /// </summary>
        internal static string toolbox_RotateInPlace {
            get {
                return ResourceManager.GetString("toolbox_RotateInPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Randomly.
        /// </summary>
        internal static string toolbox_RotateRandomly {
            get {
                return ResourceManager.GetString("toolbox_RotateRandomly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Tools.
        /// </summary>
        internal static string toolbox_RotationTools_Tooltip {
            get {
                return ResourceManager.GetString("toolbox_RotationTools_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Position.
        /// </summary>
        internal static string toolbox_SetPosition {
            get {
                return ResourceManager.GetString("toolbox_SetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope Objects.
        /// </summary>
        internal static string toolbox_SlopeObjects {
            get {
                return ResourceManager.GetString("toolbox_SlopeObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Object Height.
        /// </summary>
        internal static string toolbox_ToObjectHeight {
            get {
                return ResourceManager.GetString("toolbox_ToObjectHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Terrain Height.
        /// </summary>
        internal static string toolbox_ToTerrainHeight {
            get {
                return ResourceManager.GetString("toolbox_ToTerrainHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string whatsNew {
            get {
                return ResourceManager.GetString("whatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asc.
        /// </summary>
        internal static string xml_Asc {
            get {
                return ResourceManager.GetString("xml_Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string xml_Date {
            get {
                return ResourceManager.GetString("xml_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the file &apos;{0}&apos; permanently?.
        /// </summary>
        internal static string xml_DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("xml_DeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        internal static string xml_DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("xml_DeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete saved selection.
        /// </summary>
        internal static string xml_DeleteLabel {
            get {
                return ResourceManager.GetString("xml_DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc.
        /// </summary>
        internal static string xml_Desc {
            get {
                return ResourceManager.GetString("xml_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string xml_Export {
            get {
                return ResourceManager.GetString("xml_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string xml_Import {
            get {
                return ResourceManager.GetString("xml_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string xml_Name {
            get {
                return ResourceManager.GetString("xml_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        internal static string xml_OpenFolder {
            get {
                return ResourceManager.GetString("xml_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exists.
        ///Do you want to overwrite it?.
        /// </summary>
        internal static string xml_OverwriteMessage {
            get {
                return ResourceManager.GetString("xml_OverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite file.
        /// </summary>
        internal static string xml_OverwriteTitle {
            get {
                return ResourceManager.GetString("xml_OverwriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string xml_Restore {
            get {
                return ResourceManager.GetString("xml_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import the selection to the position it was exported.
        /// </summary>
        internal static string xml_Restore_Tooltip {
            get {
                return ResourceManager.GetString("xml_Restore_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selection is empty or invalid..
        /// </summary>
        internal static string xml_SelectionInvalidMessage {
            get {
                return ResourceManager.GetString("xml_SelectionInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection invalid.
        /// </summary>
        internal static string xml_SelectionInvalidTitle {
            get {
                return ResourceManager.GetString("xml_SelectionInvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string xml_Size {
            get {
                return ResourceManager.GetString("xml_Size", resourceCulture);
            }
        }
    }
}
