//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveIt.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoveIt.Localization.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulldoze.
        /// </summary>
        internal static string baseUI_Bulldoze_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_Bulldoze_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Alt+Click to duplicate in-place).
        /// </summary>
        internal static string baseUI_Clone_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_Clone_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Terrain.
        /// </summary>
        internal static string baseUI_FollowTerrain_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_FollowTerrain_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marquee Selection.
        /// </summary>
        internal static string baseUI_Marquee_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_Marquee_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move It.
        /// </summary>
        internal static string baseUI_MoveItButton {
            get {
                return ResourceManager.GetString("baseUI_MoveItButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Selection.
        /// </summary>
        internal static string baseUI_Single_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_Single_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Grid.
        /// </summary>
        internal static string baseUI_ToggleGrid_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_ToggleGrid_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Procedural Objects.
        /// </summary>
        internal static string baseUI_TogglePO_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_TogglePO_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Snapping.
        /// </summary>
        internal static string baseUI_ToggleSnapping_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_ToggleSnapping_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Underground View.
        /// </summary>
        internal static string baseUI_ToggleUnderground_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_ToggleUnderground_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        internal static string baseUI_Toolbox_Tooltip {
            get {
                return ResourceManager.GetString("baseUI_Toolbox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        internal static string filter_Buildings {
            get {
                return ResourceManager.GetString("filter_Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decals.
        /// </summary>
        internal static string filter_Decals {
            get {
                return ResourceManager.GetString("filter_Decals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fences.
        /// </summary>
        internal static string filter_Fences {
            get {
                return ResourceManager.GetString("filter_Fences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes.
        /// </summary>
        internal static string filter_Nodes {
            get {
                return ResourceManager.GetString("filter_Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string filter_Others {
            get {
                return ResourceManager.GetString("filter_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        internal static string filter_Paths {
            get {
                return ResourceManager.GetString("filter_Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker.
        /// </summary>
        internal static string filter_Picker {
            get {
                return ResourceManager.GetString("filter_Picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick an object to filter for objects of the same type.
        /// </summary>
        internal static string filter_Picker_Tooltip {
            get {
                return ResourceManager.GetString("filter_Picker_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO.
        /// </summary>
        internal static string filter_PO {
            get {
                return ResourceManager.GetString("filter_PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerlines.
        /// </summary>
        internal static string filter_Powerlines {
            get {
                return ResourceManager.GetString("filter_Powerlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Props.
        /// </summary>
        internal static string filter_Props {
            get {
                return ResourceManager.GetString("filter_Props", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roads.
        /// </summary>
        internal static string filter_Roads {
            get {
                return ResourceManager.GetString("filter_Roads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segments.
        /// </summary>
        internal static string filter_Segments {
            get {
                return ResourceManager.GetString("filter_Segments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surfaces.
        /// </summary>
        internal static string filter_Surfaces {
            get {
                return ResourceManager.GetString("filter_Surfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        internal static string filter_Tracks {
            get {
                return ResourceManager.GetString("filter_Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trees.
        /// </summary>
        internal static string filter_Trees {
            get {
                return ResourceManager.GetString("filter_Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move things.
        /// </summary>
        internal static string mod_description {
            get {
                return ResourceManager.GetString("mod_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-close Toolbox menu.
        /// </summary>
        internal static string options_AutoCloseToolbox {
            get {
                return ResourceManager.GetString("options_AutoCloseToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string setpos_A_Tooltip {
            get {
                return ResourceManager.GetString("setpos_A_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string setpos_Go {
            get {
                return ResourceManager.GetString("setpos_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string setpos_H_Tooltip {
            get {
                return ResourceManager.GetString("setpos_H_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string setpos_Title {
            get {
                return ResourceManager.GetString("setpos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert To PO.
        /// </summary>
        internal static string toolbox_ConvertToPO {
            get {
                return ResourceManager.GetString("toolbox_ConvertToPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Selection.
        /// </summary>
        internal static string toolbox_ExportSelection {
            get {
                return ResourceManager.GetString("toolbox_ExportSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Tools.
        /// </summary>
        internal static string toolbox_HeightTools_Tooltip {
            get {
                return ResourceManager.GetString("toolbox_HeightTools_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Selection.
        /// </summary>
        internal static string toolbox_ImportSelection {
            get {
                return ResourceManager.GetString("toolbox_ImportSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Up Objects.
        /// </summary>
        internal static string toolbox_LineUpObjects {
            get {
                return ResourceManager.GetString("toolbox_LineUpObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Objects.
        /// </summary>
        internal static string toolbox_MirrorObjects {
            get {
                return ResourceManager.GetString("toolbox_MirrorObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Tools.
        /// </summary>
        internal static string toolbox_OtherTools_Tooltip {
            get {
                return ResourceManager.GetString("toolbox_OtherTools_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Objects.
        /// </summary>
        internal static string toolbox_ResetObjects {
            get {
                return ResourceManager.GetString("toolbox_ResetObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate At Centre.
        /// </summary>
        internal static string toolbox_RotateAtCentre {
            get {
                return ResourceManager.GetString("toolbox_RotateAtCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate In-Place.
        /// </summary>
        internal static string toolbox_RotateInPlace {
            get {
                return ResourceManager.GetString("toolbox_RotateInPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Randomly.
        /// </summary>
        internal static string toolbox_RotateRandomly {
            get {
                return ResourceManager.GetString("toolbox_RotateRandomly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Tools.
        /// </summary>
        internal static string toolbox_RotationTools_Tooltip {
            get {
                return ResourceManager.GetString("toolbox_RotationTools_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Position.
        /// </summary>
        internal static string toolbox_SetPosition {
            get {
                return ResourceManager.GetString("toolbox_SetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope Objects.
        /// </summary>
        internal static string toolbox_SlopeObjects {
            get {
                return ResourceManager.GetString("toolbox_SlopeObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Object Height.
        /// </summary>
        internal static string toolbox_ToObjectHeight {
            get {
                return ResourceManager.GetString("toolbox_ToObjectHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Terrain Height.
        /// </summary>
        internal static string toolbox_ToTerrainHeight {
            get {
                return ResourceManager.GetString("toolbox_ToTerrainHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the file &apos;{0}&apos; permanently?.
        /// </summary>
        internal static string xml_DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("xml_DeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        internal static string xml_DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("xml_DeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete saved selection.
        /// </summary>
        internal static string xml_DeleteLabel {
            get {
                return ResourceManager.GetString("xml_DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string xml_Export {
            get {
                return ResourceManager.GetString("xml_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string xml_Import {
            get {
                return ResourceManager.GetString("xml_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exists.
        ///Do you want to overwrite it?.
        /// </summary>
        internal static string xml_OverwriteMessage {
            get {
                return ResourceManager.GetString("xml_OverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite file.
        /// </summary>
        internal static string xml_OverwriteTitle {
            get {
                return ResourceManager.GetString("xml_OverwriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string xml_Restore {
            get {
                return ResourceManager.GetString("xml_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import the selection to the position it was exported.
        /// </summary>
        internal static string xml_Restore_Tooltip {
            get {
                return ResourceManager.GetString("xml_Restore_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selection is empty or invalid..
        /// </summary>
        internal static string xml_SelectionInvalidMessage {
            get {
                return ResourceManager.GetString("xml_SelectionInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection invalid.
        /// </summary>
        internal static string xml_SelectionInvalidTitle {
            get {
                return ResourceManager.GetString("xml_SelectionInvalidTitle", resourceCulture);
            }
        }
    }
}
